### ISSUE TITLE
Details for results in Table 2

### ISSUE THREAD

**Issue by fwzlaughing** [miafei/NodeNorm#1]
Dear authors,
    I am very interested in your work, but I can't reproduce the results reported in Table 2 in the paper. Could you provide the hyperparameter details for that? Thanks very much!

**Comment by miafei** [comment]
Hi,
Thanks for your interest. Please refer to table 7 in the Appendix of the paper.

**Comment by yanghu819** [comment]
Where can I find the appendix of the paper?

**Comment by miafei** [comment]
> Where can I find the appendix of the paper?

You can find the hyperparameters in Tab.23 of https://arxiv.org/pdf/2006.07107v2.pdf.
