### ISSUE TITLE
Detailed settings for Tab.2

### ISSUE THREAD

**Issue by hhr114** [miafei/NodeNorm#2]
Hi,
  I am very appreciate your work. I have some troubles with reproduce the results in Tab. 2 when the number of layers is more than 8. Although I have refered Tab. 7 in appendix and tried the following script, the problem is still staying. Could anybody help me?

`python main.py with data.dataset=cora arch.layer_type=gcn arch.block_type=n_a arch.num_layers=8 arch.dropout.p=0.9 optim.l1_weight=0.0001 optim.weight_decay=0.0005 gpu_id=0`

**Comment by miafei** [comment]
Hi,

Thanks for your interest in our work. Please use arch.layer_type=gcn_res arch.block_type=n_a_r. As stated in our paper, we add residucal connections to avoid graidient vanishing.

**Comment by miafei** [comment]
> Hi,
> I am very appreciate your work. I have some troubles with reproduce the results in Tab. 2 when the number of layers is more than 8. Although I have refered Tab. 7 in appendix and tried the following script, the problem is still staying. Could anybody help me?
> 
> `python main.py with data.dataset=cora arch.layer_type=gcn arch.block_type=n_a arch.num_layers=8 arch.dropout.p=0.9 optim.l1_weight=0.0001 optim.weight_decay=0.0005 gpu_id=0`

Hi,

Thanks for your interest in our work. Please use arch.layer_type=gcn_res arch.block_type=n_a_r. As stated in our paper, we add residucal connections to avoid graidient vanishing.
