### ISSUE TITLE
the mean of nn_type

### ISSUE THREAD

**Issue by MrAirplaneLu** [miafei/NodeNorm#3]
![image](https://user-images.githubusercontent.com/45754132/120989751-7373b100-c7b2-11eb-834e-f7560705451f.png)
Hello, what do different nn_type mean?
thank you!

**Comment by miafei** [comment]
node_v is our NodeNorm1, node_srv is NodeNorm2, node_m is the mean subtraction operation. node_pr_3 is NodeNorm3. (node_pr_$p is NodeNormp)

**Comment by MrAirplaneLu** [comment]
Thank you very much.
