### ISSUE TITLE
Code for missing feature？

### ISSUE THREAD

**Issue by yanghu819** [miafei/NodeNorm#4]
Amazing job, How can I reproduce the result of missing feature?

**Comment by miafei** [comment]
Sorry the code is not there. But it's simple to reproduce by two lines of code: keep all the training nodes features, and replace all non-training node features to 0.

**Comment by yanghu819** [comment]
Thank you for your reply, I think missing feature means: use no feature at
all but with only adjacency information. Your missing feature setting is:
keep training feature and set testing and validation feature to be 0 right?

miafei ***@***.***> 于2022年2月9日周三 11:16写道：

**Comment by miafei** [comment]
Yes. I followed the setting in [1].  They proposed this missing feature setting.

[1]Zhao, L., & Akoglu, L. (2019). Pairnorm: Tackling oversmoothing in gnns. arXiv preprint arXiv:1909.12223.

**Comment by yanghu819** [comment]
Thank you so much! Great work!

miafei ***@***.***> 于2022年2月9日周三 17:18写道：
